version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - AWS_REGION=us-east-1
      - DYNAMODB_TABLE_NAME=HangmanPlayers
      - DYNAMODB_USE_LOCAL=true
      - DYNAMODB_LOCAL_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
    ports:
      - '8000:8000'
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

volumes:
  dynamodb_data: {}
